name: Build/Test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.14
      - uses: snok/install-poetry@v1
      - name: Install dependencies
        run: make install
      - name: Lint/analyze source
        run: make lint
      - name: Spell check
        uses: streetsidesoftware/cspell-action@v8
        with:
          incremental_files_only: false # imperfectt
          check_dot_files: true
      - name: Run tests
        env:
          TERM: "dumb"
        run: make test
