name: Publish Package
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.14
      - uses: snok/install-poetry@v1
      - name: Install dependencies
        run: make install
      - name: Lint/analyze source
        run: make lint
      - name: Run tests
        env:
          TERM: "dumb"
        run: make test
      - name: Create package
        run: |
          make package
          rm -rf dist/pyinstaller/
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: albums-package
          path: dist/

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Use OIDC permissions for trusted publishing
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: albums-package
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
